main: ${PACKAGE}.FastHopperPlugin
name: ${NAME}
version: "${VERSION}"
api-version: "1.21.8"
folia-supported: true
author: Gaasu9041
description: fasthopper for toritorismp
commands:
  fasthopper:
    description: Configure FastHopper.
    usage: "/<command> transfar <1-64> | tick <ticks> | reload"
    aliases:
      - fh
permissions:
  fasthopper.admin:
    description: allows changing fasthopper settings
    default: op
